source "https://rubygems.org"
ruby "~> 3.0.5"
gem "rack", ">= 2.0.8"
gem "rack-contrib"
gem "puma", ">= 3.12.2"
gem "sinatra"
gem "i18n"
gem "pony"
gem "json"
gem "google-cloud-secret_manager"
gem "sinatra-flash"
