source "https://rubygems.org"
ruby "~> 3.4.9"
gem "rack", "~> 3.0"
gem "rack-contrib"
gem "puma", "~> 7.2"
gem "sinatra", "~> 4.1"
gem "i18n"
gem "pony"
gem "json"
gem "google-cloud-secret_manager"
gem "sinatra-flash"
